### PR TITLE
Resource configuration in build and test page

### PR DESCRIPTION
**Pull request by facethesunsea**
### What this PR does / Why we need it:

- add local cluster and advanced configuration
- build and test can select cluster and namespace

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

### Check List 

- [ ] Docs have been added / updated
- [ ] Unit test / Integration test for the changes have been added
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

## More information

### CODE REVIEW

**Comment by flyer103** [comment]
Change all Chinese comments to English.

**Comment by flyer103** [comment]
Can we change all Chinese to English and adapt the local language through i18n?

**Comment by facethesunsea** [comment]
> Can we change all Chinese to English and adapt the local language through i18n?

can not

**Review by leozhang2018 — CHANGES_REQUESTED** [review]

**Review by leozhang2018 — APPROVED** [review]
LGTM

**Pull request merged**
